version: '2'

services:
  web1:
    container_name: web1
    build: ./apache
    ports:
      - 8001:80
    volumes:
      - ./apache/log1/:/var/log/apache2/
  web2:
    container_name: web2
    build: ./apache
    ports:
      - 8002:80
    volumes:
      - ./apache/log2/:/var/log/apache2/
